zlm:
  enable: true
  hook-enable: true
  balance: round_robin
  nodes:
    - server-id: zlm
      host: "http://127.0.0.1"
      secret: your_secret
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true