zlm:
  enable: true
  hook-enable: true
  balance: round_robin
  nodes:
    - node-id: "zlm"
      host: "http://127.0.0.1"
      secret: your_secret

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true